# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = 'backup-testbox'

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = 'http://dl.dropbox.com/u/95700067/backup-testbox.box'

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  config.vm.share_folder 'project-root', '/backup.git', '../'

  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui
end
